spring:
  dubbo:
    appname: spring-boot-starter-dubbo-consumer-test
    registry: zookeeper://127.0.0.1:2181?backup=127.0.0.1:2182,127.0.0.1:2183
    protocol: dubbo
    serialization: protobuf


server:
  port: 8089